name: publish
on:
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string
        default: ''

permissions:
  contents: 'read'
  id-token:  'write'

jobs:
  publish-greenhouse-image:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.build-publish.outputs.imageid }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - run: ./scripts/bundle-publish.sh
